### ISSUE TITLE
Error while runing  script

### ISSUE THREAD

**Issue by Rabson** [aliazlan4/redis-npm-server#1]
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./redis-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)     
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {   
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./redis-server',
  path: './redis-server',
  spawnargs: [ '--port 6379' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redis@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redis@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by aliazlan4** [comment]
Please explain your running process and environment.

**Comment by Rabson** [comment]
Operating system is Windows 10. All the error log i got as i was runing the script.
